# Generated by Django 4.0.4 on 2022-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='type',
            field=models.IntegerField(choices=[(1, 'Consulta'), (2, 'Sugerencias'), (3, 'Errores'), (4, 'Otro')], default=1),
        ),
    ]
