# Generated by Django 4.0.4 on 2022-06-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='type',
            field=models.IntegerField(choices=[[1, 'Consulta'], [2, 'Sugerencias'], [3, 'Errores'], [4, 'Otro']], verbose_name=''),
        ),
    ]
