# Generated by Django 4.0.4 on 2022-06-03 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_email_alter_contacts_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
