# Generated by Django 4.0.4 on 2022-06-04 17:28

from django.db import migrations

def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    book_model = apps.get_model('login', 'User')
    book_model.objects.create (
        id = 1,
        password = "pbkdf2_sha256$320000$DM76IWlDft1Qf17JdbOfEh$oaYfDd9rVngiw42hxsd7yAhuKsZhwz/DC31ZcyaBoA0=",
        is_superuser = 1,
        username = "caracena",
        first_name = "Cesar",
        last_name = "Aracena",
        email = "aracenameister@gmail.com",
        is_staff = 1,
        is_active = 1,
        date_joined = "2022-06-01 17:13:10",
        bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam luctus, dolor volutpat gravida suscipit, ex risus dignissim felis, eget placerat mauris lorem gravida metus. Morbi pharetra elit rutrum, vehicula nisl eu, eleifend tellus. Nulla volutpat feugiat enim, vel suscipit enim semper et. Proin ne.",
        avatar = "cesar.png"
        )
    book_model.objects.create (
        id = 2,
        password = "pbkdf2_sha256$320000$h7g6DUs5nyAHO9o3e4rw9u$F6lDRNnjlCXxf901XtjdNaoVfgngclIwi5zsLUjcLhY=",
        is_superuser = 1,
        username = "jorozco",
        first_name = "Jose",
        last_name = "Orozco",
        email = "joqui@gmail.com",
        is_staff = 1,
        is_active = 1,
        date_joined = "2022-06-01 19:29:03",
        bio = "Aenean tellus orci, accumsan sit amet bibendum vitae, iaculis nec tortor. Proin accumsan, neque ac tempus cursus, leo mauris vulputate massa, ut blandit ex libero eget dui. Ut ut neque neque. Vivamus tincidunt rhoncus elit. Cras sagittis feugiat pretium. Pellentesque vehicula tincidunt dignissim. M.",
        avatar = "joqui.jpeg"
        )
    book_model.objects.create (
        id = 3,
        password = "pbkdf2_sha256$320000$WJ6SxiOCKjjf2A7wLdncWx$8sGNeIStA2nl0/k3fvDIb4xEsax9tpq49TwpvBwiYFs=",
        is_superuser = 1,
        username = "eorozco",
        first_name = "Esteban",
        last_name = "Orozco",
        email = "esteban@gmail.com",
        is_staff = 1,
        is_active = 1,
        date_joined = "2022-06-02 14:09:53",
        bio = "Etiam pulvinar eros sed tincidunt mollis. Nam maximus tincidunt urna, id pretium eros facilisis vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi ut sem.",
        avatar = "esteban3.jpg"
        )
    book_model.objects.create (
        id = 4,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 1,
        username = "admin",
        email = "admin@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "",
        avatar = "avatar.jpg"
        )
    book_model.objects.create (
        id = 5,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 0,
        username = "juan",
        first_name = "Juan",
        last_name = "Hundt",
        email = "juan@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "",
        avatar = "avatar.jpg"
        )
    book_model.objects.create (
        id = 6,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 0,
        username = "silvana",
        first_name = "Silvana",
        last_name = "Orozco",
        email = "silvana@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "Hola, soy Silo",
        avatar = "avatar.jpg"
        )
    book_model.objects.create (
        id = 7,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 0,
        username = "carmen",
        first_name = "Carmen",
        last_name = "Orozco",
        email = "carmuncha@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "",
        avatar = "avatar.jpg"
        )
    book_model.objects.create (
        id = 8,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 0,
        username = "rolo",
        first_name = "Rolando",
        last_name = "Romero",
        email = "rome@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "",
        avatar = "avatar.jpg"
        )
    book_model.objects.create (
        id = 9,
        password = "pbkdf2_sha256$320000$u0GxiiJO2kmOYUbG8GatUT$SVWzb4+EXi1kS2ABqi7CSm+EVPirlTxsuuj7nhC+0t8=",
        is_superuser = 0,
        username = "gunso",
        first_name = "Emmanuel",
        last_name = "Gunst",
        email = "elmasgunso@email.com",
        is_staff = 0,
        is_active = 1,
        date_joined = "2022-06-04 17:39:03",
        bio = "",
        avatar = "avatar.jpg"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
