# Generated by Django 4.0.4 on 2022-06-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_contactenos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactenos',
        ),
    ]
