# Generated by Django 4.0.4 on 2022-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[[1, 'Consulta'], [2, 'Sugerencia'], [3, 'Error'], [4, 'Otro']], verbose_name=''),
        ),
    ]
