# Generated by Django 4.0.4 on 2022-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='last_name',
        ),
    ]
