# Generated by Django 4.0.4 on 2022-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='avatar.jpg', null=True, upload_to='')),
            ],
        ),
    ]
