# Generated by Django 4.0.4 on 2022-06-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
