# Generated by Django 4.0.4 on 2022-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_about_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='info',
            field=models.TextField(max_length=300),
        ),
    ]
