# Generated by Django 4.0.4 on 2022-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_about_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bday',
            field=models.DateField(default=True),
        ),
    ]
