# Generated by Django 4.0.4 on 2022-06-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_about_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bday',
            field=models.DateField(default='0'),
        ),
    ]
