# Generated by Django 4.0.4 on 2022-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_about_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bday',
            field=models.DateField(),
        ),
    ]
