# Generated by Django 4.0.4 on 2022-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_about_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
